alteração no UserController ,LoginRepository ,migrate create tabela u…
SouJunior-Labs/labs-api pull request #5
Opened 2024-05-10 20:36 UTC by lthurler

…sers e UserRegisterRequest para incluir os campos: cidade,estado e discord

2024-05-13 16:37 UTC, rigonlucas requested changes
Realizar rollback do docker-compose

2024-05-13 16:37 UTC, rigonlucas commented on docker-compose.yml
> +    entrypoint: [ "php", "/opt/www/bin/hyperf.php", "server:watch" ]
Este arquivo não pode ser alterado
- realizar o rollback dele

2024-05-13 19:39 UTC, rigonlucas commented
@lthurler alguns pontos a serem considerados:

- [ ] coloca o link da task na descrição da tarefa
- [ ] descrever brevemente o que foi realizado

2024-05-13 20:26 UTC, rigonlucas requested changes
Revisar migrations.
Qualquer coisa me chama que te explico a questão

2024-05-13 20:26 UTC, rigonlucas commented on migrations/2024_01_25_210912_create_users_table.php
> +            $table->string('cidade', 32);
Revisar a quantidade de caracteres no campo. 32 é pouco

- Revisar os campos abaixo na questão de caracteres

2024-05-13 20:26 UTC, rigonlucas commented on migrations/2024_01_25_210912_create_users_table.php
> +            $table->string('cidade', 32);
aqui vc precisa alterar, criar uma nova migration e adicionar os campos lá.

- Primeiro ponto, migrations são rodadas uma após a outra. Neste caso vc preci fazer isso em outro arquivo
- Rodar esse command cria um migration: **php bin/hyperf.php gen:migration alter_users_table --table=users**
- Após isso rodar o commando de migration: **php bin/hyperf.php migrate**
- LEMBRAR DE ADICIONAR A REMOÇÃO DOS DADOS QUE FGORAM INCLUÍDOS NO MÉTODO 
- -public function down(): void
- - É necessário aidionar cada ampo separadamente.

2024-05-22 22:21 UTC, rigonlucas commented on migrations/2024_01_25_210912_create_users_table.php
> +            $table->string('permission',20)->nullable();
remover esta coluna, já existe

2024-05-22 22:23 UTC, rigonlucas commented on migrations/2024_01_25_210912_create_users_table.php
> +            $table->string('linkedin',60)->nullable();
coluna já existe

2024-05-24 13:29 UTC, lthurler commented
coloca o link da task na descrição da tarefa ok
descrever brevemente o que foi realizado ok

2024-05-24 13:29 UTC, lthurler commented
ok feito

2024-05-24 21:26 UTC, Guilherme-Silva0 commented on docker-compose1.yml
Esse arquivo deveria está nos commits?

2024-05-27 22:44 UTC, rigonlucas commented on docker-compose1.yml
Quando der um tempo vamos realizar algumas melhorias nele :-)

2024-05-27 22:45 UTC, rigonlucas commented on storage/swagger/http.json
> +{"openapi":"3.0.0","paths":{"\/index":{"get":{"tags":["\/Index"],"summary":"GET example","operationId":"c7a3e07c42ef883719b986d0d3195666","responses":{"200":{"description":"Description of the returne
Indentação do objeto

2024-06-10 17:52 UTC, rigonlucas commented on storage/swagger/http.json
> +{"openapi":"3.0.0","paths":{"\/index":{"get":{"tags":["\/Index"],"summary":"GET example","operationId":"c7a3e07c42ef883719b986d0d3195666","responses":{"200":{"description":"Description of the returne
@lthurler revisar isso aqui

2024-06-11 19:57 UTC, rigonlucas approved these changes

2024-06-11 20:07 UTC, Guilherme-Silva0 approved these changes

2024-06-12 01:03 UTC, figmateus approved these changes
legit, veja depois apenas os campos que sao obrigatorios e estao como nullables na migration

2024-06-12 01:03 UTC, figmateus commented on migrations/2024_01_25_210912_create_users_table.php
> +            $table->string('discord',30)->nullable();
se os campos discord e linkedin sao obrigatorios porque eles podem ser nulos ?

2024-06-12 01:36 UTC, rigonlucas commented on migrations/2024_01_25_210912_create_users_table.php
> +            $table->string('discord',30)->nullable();
Boa pergunta. 
Essa base da dados já existe, entao usuários anteriores a está feature devem ficar como null

2024-06-13 23:31 UTC, merged