Corrigindo bug de retorno das permissões do usuário
SouJunior-Labs/labs-api pull request #9
Opened 2024-06-26 23:39 UTC by Guilherme-Silva0

Ao retornar o usuário, as permissões estavam indo como resposta em forma de texto no padrão normalize do php, alterei para que sejam retornadas em forma de objeto.

2024-06-27 00:01 UTC, rigonlucas requested changes
confere o que disse nos comentários e for possível alterar

2024-06-27 00:01 UTC, rigonlucas commented on app/Controller/UserController.php
> +            $user[$key]['permissions'] = unserialize($value['permissions']);
Aqui provavelmente é uma collection. Como está vando esta lista?

2024-06-27 00:01 UTC, rigonlucas commented on app/Controller/UserController.php
> +            $user[$key]['permissions'] = unserialize($value['permissions']);
também é possível fazer isso no ORM. 
No model tem o attribute que você pode fazer o cost 
olha na doc

2024-06-28 10:20 UTC, Guilherme-Silva0 commented on app/Controller/UserController.php
> +            $user[$key]['permissions'] = unserialize($value['permissions']);
> Aqui provavelmente é uma collection. Como está vando esta lista?

Essas permissions estão sendo salva no banco como uma string, elas estavam sendo mandadas diretamente sem transformar em objeto antes, mas quando eu tiver um tempinho irei dá uma olhada sim na doc.

2024-06-29 00:18 UTC, rigonlucas approved these changes

2024-06-29 00:20 UTC, rigonlucas commented on app/Controller/UserController.php
> +            $user[$key]['permissions'] = unserialize($value['permissions']);
Ta apravado 
Antes de fechar confere isso 
Pode madar um print do response

2024-07-01 16:38 UTC, rigonlucas approved these changes

2024-07-01 17:54 UTC, lthurler approved these changes

2024-07-01 23:44 UTC, figmateus approved these changes

2024-07-02 21:45 UTC, merged